services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  nestjs:
    build:
      context: ./backend-api
      dockerfile: Dockerfile
    container_name: nestjs_app
    restart: always
    depends_on:
      - mysql
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "3000:3000"
    volumes:
      - ./backend-api:/app
      - /app/node_modules # 빈 익명 볼륨으로 마운트해서 로컬 node_modules가 덮어씌우지 않도록 막는다.

volumes:
  mysql_data:
